export const LOGIN_CURRENT_USER = "LOGIN_CURRENT_USER_PENDING";
export const LOGIN_CURRENT_USER_SUCCESS = "LOGIN_CURRENT_USER_SUCCESS";
export const LOGIN_CURRENT_USER_FAILURE = "LOGIN_CURRENT_USER_FAILURE";