/* User Action */
export const LOGIN_CURRENT_USER = "LOGIN_CURRENT_USER_PENDING";
export const LOGIN_CURRENT_USER_SUCCESS = "LOGIN_CURRENT_USER_SUCCESS";
export const LOGIN_CURRENT_USER_FAILURE = "LOGIN_CURRENT_USER_FAILURE";
/* get expenses Action */
export const GET_CURRENT_USER_EXPENSE = "GET_CURRENT_USER_EXPENSE_PENDING";
export const GET_CURRENT_USER_EXPENSE_SUCCESS = "GET_CURRENT_USER_EXPENSE_SUCCESS";
export const GET_CURRENT_USER_EXPENSE_FAILURE = "GET_CURRENT_USER_EXPENSE_FAILURE";
/* set expenses Action */
export const SET_CURRENT_USER_EXPENSE = "SET_CURRENT_USER_EXPENSE_PENDING";
export const SET_CURRENT_USER_EXPENSE_SUCCESS = "SET_CURRENT_USER_EXPENSE_SUCCESS";
export const SET_CURRENT_USER_EXPENSE_FAILURE = "SET_CURRENT_USER_EXPENSE_FAILURE";